name: Update Valorant Stats

on:
  schedule:
    # Agendamento para Sábado (6) e Domingo (0)
    - cron: '0 0 * * 6,0'
  workflow_dispatch: # Permite rodar manualmente pelo botão no GitHub

jobs:
  run-etl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r Relatorio_valorant/src/etl/requirements.txt

      - name: Executar Script de ETL
        env:
          # Mapeia os segredos do GitHub para as variáveis de ambiente do script
          user: ${{ secrets.user }}
          password: ${{ secrets.password }}
          host: ${{ secrets.host }}
          port: ${{ secrets.port }}
          dbname: ${{ secrets.dbname }}
        run: python Relatorio_valorant/src/etl/script.py
